name: Release

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose
  create-release:
    name: deploy
    needs: [test]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [
            aarch64-unknown-linux-gnu,
            x86_64-unknown-linux-gnu,
            i686-pc-windows-gnu,
            x86_64-pc-windows-gnu,
            # aarch64-apple-darwin,
            # x86_64-apple-darwin,
          ]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: install musl
        run: sudo apt install musl-tools
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          # TODO:
          # strip target/${{ matrix.target }}/release/gitlab-tui

          cd target/${{ matrix.target }}/release          
          rm -r ./build ./deps examples gitlab-tui.d incremental ./.fingerprint .cargo-lock
          tar cvzf ../../../gitlab-tui-${{ matrix.target }}.tar.gz ./
          cd -

      - name: Publish
        uses: softprops/action-gh-release@v1
        # TODO: if any of the build step fails, the release should be deleted.
        with:
          files: "gitlab-tui*"
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
